/*
format is:
['some jql', // the jql under test
    2, // the index of the cursor in the text
    // an array of expected suggestions (use NONE for empty array)
    [],
    // an array of suggestions that should NOT be in the results
    [],
],
*/

export const suggestorTestData = [
    [`project = V`, 11, ['"VSCODE"', '"VTC"', 'VTS', 'VTN'], []],
    [`assignee = currentUser()  project = VTC`, 25, ['and', 'or', 'order by'], []],
    [`assignee = currentUser()`, 24, ['NONE'], ['and', 'or', 'order by']],
    [`project in(projectsLeadByUser(),) `, 33, ['and', 'or', 'order by'], []],
    [`project in(projectsLeadByUser(),) `, 32, ['"VSCODE"', '"VTC"', 'VTS', 'VTN'], []],
    [`project in projectsWhereUserHasRole("") `, 38, ['NONE'], []],
    [`project in projectsWhereUserHasRole("" ) `, 39, ['NONE'], []],
    [`NOT `, 4, ['(', 'project'], []],
    [
        `status `,
        7,
        ['=', '!=', 'is not', 'is', 'not in', 'in', 'was', 'was not', 'was in', 'was not in', 'changed'],
        [],
    ],
    [``, 0, ['project'], []],
    [`pro`, 3, ['project'], []],
    [`pro`, 0, ['project'], []],
    [`pro `, 3, ['project'], []],
    [`pro `, 2, ['project'], []],
    [`(`, 0, ['project'], []],
    [`(`, 1, ['project'], []],
    [` ( `, 0, [], []],
    [`(    `, 5, ['project'], []],
    [`(pro`, 4, ['project'], []],
    [`(pro and )`, 4, ['project'], []],
    [`project in ("Jira Support Test" `, 32, [')', ','], ['VTS']],
    [`project in(projectsLeadByUser(), "Another Project") `, 52, ['and', 'or', 'order by'], [')', ',']],
    [`project in( ,)`, 12, ['"VSCODE"', '"VTC"', 'VTS', 'VTN'], ['project']],
    [
        `project = "Another Project" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        0,
        ['(', 'not', 'project'],
        [],
    ],
    [
        `project = "Another Project" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        1,
        ['project'],
        ['('],
    ],
    [
        `project = "Another Project" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        7,
        ['project'],
        ['('],
    ],
    [
        `project = "Another Project" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        8,
        ['=', '!=', 'in', 'is', 'is not', 'not in'],
        ['('],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        10,
        ['"VSCODE"', '"VTC"', 'VTS', 'VTN', 'Some Project', '"Quoted Project"'],
        [],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        12,
        ['"VSCODE"', '"VTC"', 'VTS', 'VTN'],
        ['Some Project', '"Quoted Project"'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        13,
        ['"VSCODE"'],
        ['"VTC"', 'VTS', 'VTN', 'Some Project', '"Quoted Project"'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        18,
        ['"VSCODE"'],
        ['AND', '"VTC"', 'VTS', 'VTN', 'Some Project', '"Quoted Project"'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        19,
        ['and', 'or', 'order by'],
        ['"VSCODE"', '"VTC"', 'VTS', 'VTN', 'Some Project', '"Quoted Project"'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        20,
        ['and'],
        ['or', 'order by'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        22,
        ['and'],
        ['or', 'order by'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        23,
        [],
        ['and', 'or', 'order by'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        24,
        ['fixVersion', 'filter', 'flagname'],
        ['('],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        25,
        ['fixVersion', 'filter', 'flagname'],
        ['('],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        26,
        ['fixVersion', 'filter'],
        ['(', 'flagname'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        27,
        ['fixVersion'],
        ['filter', '(', 'flagname'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        34,
        ['fixVersion'],
        ['filter', '(', 'flagname'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        35,
        [
            '=',
            '>',
            '<',
            'in',
            '<=',
            '>=',
            'is',
            '!=',
            'was',
            'is not',
            'not in',
            'was in',
            'changed',
            'was not',
            'was not in',
        ],
        ['fixversion'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        36,
        ['in', 'is', 'is not'],
        ['=', '>', '<', '<=', '>=', '!=', 'was', 'not in', 'was in', 'changed', 'was not', 'was not in'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        38,
        ['unreleasedVersions()', '("VSCODE"', '("VTC"', '(VTS', '(VTN', '(Some Project', '("Quoted Project"'],
        ['in'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        39,
        ['unreleasedVersions()'],
        ['("VSCODE"', '("VTC"', '(VTS', '(VTN', '(Some Project', '("Quoted Project"'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        57,
        ['unreleasedVersions()'],
        ['("VSCODE"', '("VTC"', '(VTS', '(VTN', '(Some Project', '("Quoted Project"'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        58,
        ['unreleasedVersions()'],
        ['vts'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        59,
        ['and', 'or', 'order by'],
        ['unreleasedVersions()'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        80,
        ['Vers'],
        [],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        89,
        ['and', 'or', 'order by'],
        [],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        90,
        ['NONE'],
        [],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        91,
        ['and', 'or', 'order by'],
        [],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        92,
        ['order by', 'or'],
        ['and'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        95,
        ['order by'],
        ['and', 'or'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        100,
        ['category', 'fixVersion'],
        ['and', 'or', 'currentUser()'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        109,
        [','],
        ['category'],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        110,
        ['Account.customer.id', 'category'],
        [','],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        131,
        [',', 'asc', 'desc'],
        [],
    ],
    [
        `project = "VSCODE" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        132,
        ['asc', 'desc'],
        [','],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        14,
        ['NONE'],
        [],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        15,
        ['"vscode"', '"vtc"', 'vts'],
        [],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        16,
        ['"vscode"', '"vtc"', 'vts'],
        [],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        18,
        ['"vscode"'],
        ['"vtc"', 'vts'],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        23,
        ['"vscode"'],
        ['"vtc"', 'vts'],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        24,
        ['NONE'],
        [],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        25,
        ['"vscode"', '"vtc"', 'vts'],
        [','],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        26,
        ['"vscode"', '"vtc"', 'vts'],
        [],
    ],
    [
        `fixVersion in ("VSCODE", "VTC") and issue in("VSCODE-1",linkedIssues("")) AND resolution = Unresolved`,
        28,
        ['"vtc"', 'vts'],
        ['"vscode"'],
    ],
    [
        `status was "In Progress" BY someone BEFORE now() AFTER "2019/01/01"`,
        8,
        ['was', 'was not', 'was in', 'was not in'],
        [],
    ],
    [
        `status was "In Progress" BY someone BEFORE now() AFTER "2019/01/02"`,
        11,
        ['"vscode"', '"vtc"', 'vts'],
        ['was', 'was not', 'was in', 'was not in'],
    ],
    [`status was "In Progress" BY someone BEFORE now() AFTER "2019/01/03"`, 13, ['i'], []],
    [`status was not "In Progress" DURING("2019/01/01","2019/01/15")`, 28, ['In Progress'], ['"vscode"']],
    [`status was not in ("In Progress","Resolved") ON "2019/01/16"`, 28, ['In Progr'], ['"vscode"']],
    [
        `status CHANGED FROM "In Progress" TO "Resolved" BY freddo BEFORE endOfWeek() AFTER startOfWeek()`,
        28,
        ['In Prog'],
        ['"vscode"'],
    ],
    [
        `assignee = currentUser() AND project = "Another Project" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        11,
        ['currentUser()'],
        [],
    ],
    [
        `assignee = currentUser() AND project = "Another Project" AND (fixVersion in unreleasedVersions() OR fixVersion = "Version 1.0" ) ORDER BY category , Account.customer.id ASC`,
        15,
        ['curr', 'currentUser()'],
        [],
    ],
    [``, 0, ['(', 'project'], []],
    [`p`, `p`.length, ['project'], []],
    [`project`, `project`.length, ['project'], []],
    [`project `, `project `.length, ['=', 'in', 'is', '!=', 'is not', 'not in'], ['project']],
    [`project =`, `project =`.length, ['='], ['in', 'is', '!=', 'is not', 'not in']],
    [`project = `, `project = `.length, ['"vscode"', '"vtc"', 'vts'], ['=', 'in', 'is', '!=', 'is not', 'not in']],
];
